version: '3.9'
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    command: npm run start:dev
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/cartracker
      - JWT_SECRET=changeme
      - CORS_ORIGIN=http://localhost:8080
    ports: ["5000:5000"]
    depends_on: [mongo]

  client:
    build: ./client
    command: npm run serve
    environment:
      - VUE_APP_API_BASE_URL=http://localhost:5000
      - VUE_APP_YANDEX_API_KEY=PASTE_YOUR_KEY
    ports: ["8080:8080"]
    depends_on: [server]

volumes:
  mongo_data:
